{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $release_name }}
            cron: {{ $job.name }}
        spec:
          imagePullSecrets:
{{ toYaml $.Values.image.secrets | indent 10 }}
          containers:
          - name: {{ $job.name }}
            {{- if $job.image }}
            image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
            imagePullPolicy: {{ $job.image.imagePullPolicy }}
            {{- else }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            {{- end }}
            {{- if $.Values.application.secretName }}
            envFrom:
            - secretRef:
                name: {{ $.Values.application.secretName }}
            {{- end }}
            env:
            {{- with $job.env }}
{{ toYaml . | indent 12 }}
            {{- end }}
{{- if $.Values.postgresql.managed }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-postgres
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-postgres
                  key: privateIP
{{- end }}
            - name: DATABASE_URL
              value: {{ $.Values.application.database_url | quote }}
            - name: DATABASE_HOST
              value: {{ $.Values.application.database_host | quote }}
            - name: DATABASE_PORT
              value: {{ $.Values.application.database_port | quote }}
            - name: DATABASE_USER
              value: {{ $.Values.application.database_user | quote }}
            - name: DATABASE_PASSWORD
              value: {{ $.Values.application.database_password | quote }}
            - name: DATABASE_NAME
              value: {{ $.Values.application.database_name | quote }}
{{- if $.Values.application.redis_url }}
            - name: REDIS_URL
              value: {{ $.Values.application.redis_url | quote }}
{{- end }}
            - name: GITLAB_ENVIRONMENT_NAME
              value: {{ $.Values.gitlab.envName }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}