name: Build And Release Docker Images

on:
  push:
    branches:
      - 'mariadb'

env:
  IMAGE_NAME: auto-deploy-image
  GITHUB_OWNER: larvatatw
  DOCKERHUB_OWNER: larvata
  DOCKER_DRIVER: overlay2
  ALPINE_VERSION: 3.12
  GLIBC_VERSION: 2.31-r0
  HELM_VERSION: 2.17.0
  KUBERNETES_VERSION: 1.15.12

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64
          build-args: |
            DOCKER_DRIVER=${{ env.DOCKER_DRIVER }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=${{ env.GLIBC_VERSION }}
            HELM_VERSION=${{ env.HELM_VERSION }}
            KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.GITHUB_OWNER }}/${{ env.IMAGE_NAME }}:latest
