variables:
  SAST_DISABLE_DIND: "true"
  SCAN_KUBERNETES_MANIFESTS: "true"
  SAST_DEFAULT_ANALYZERS: "kubesec,secrets"

include:
  - template: SAST.gitlab-ci.yml

stages:
  - build
  - test
  - release

.chart-job:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:alpine-helm"
  before_script:
    - cd assets/auto-deploy-app

chart:compile_manifests:
  extends: .chart-job
  stage: build
  script:
    - mkdir manifests
    - helm init --client-only --stable-repo-url=https://charts.helm.sh/stable
    - helm dependency build .
    - helm template -f values.yaml --output-dir manifests .
  artifacts:
    paths:
      - manifests

chart:lint:
  extends: .chart-job
  stage: test
  script:
    - helm lint .

kubesec-sast:
  needs: ["chart:compile_manifests"]

chart:test:
  extends: .chart-job
  stage: test
  script:
    - apk add --no-cache build-base go
    - helm init --client-only --stable-repo-url=https://charts.helm.sh/stable
    - helm dependency build .
    - cd test && GO111MODULE=auto go test .

# auto-deploy-image doesn't need to release the chart to https://charts.gitlab.io/,
# as it bundles a chart by default.
# release-chart:
#   stage: release
#   script:
#     - curl --fail --request POST --form "token=${CHARTS_TRIGGER_TOKEN}" --form ref=master
#         --form "variables[CHART_NAME]=$CI_PROJECT_NAME"
#         --form "variables[RELEASE_REF]=$CI_COMMIT_REF_NAME"
#         https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
#   only:
#     - /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\Z/@gitlab-org/charts/auto-deploy-app
